INSERT INTO "PUBLIC"."ITEM" VALUES
(1, 'TODAY', 'REAL_A', 'BEAUTY', TRUE, 1000, 10),
(2, 'NORMAL', 'REAL_B', 'FASHION', TRUE, 2000, 20),
(3, 'SLOW', 'REAL_C', 'ETC', FALSE, 3000, 30);

INSERT INTO "PUBLIC"."REGIONS" VALUES
(1, 'SEOUL'),
(1, 'INCHEON'),
(2, 'INCHEON'),
(2, 'DAEGU'),
(3, 'ULSAN'),
(3, 'BUSAN'),
(3, 'JEJU');